### ISSUE TITLE
"Wifi Backend" auto toggles off on restarting.

### ISSUE THREAD

**Issue by duke1921** [proxidize/proxidize-android#1]
Hi, 

When I enable the "Wifi Backend" setting, it says "settings saved, please restart the app."
And when I restart the app, the "Wifi Backend" setting is already disabled.
And the cycle continues forever.

And I tested this on a few phones before commenting here.
My main phone is Huawei Honor Play with 4GB RAM running Android 9.0, EMUI 9.1. (variant COR-AL00, details link: https://www.gsmarena.com/honor_play-9230.php#cor-al00  )

**Comment by botuser420** [comment]
I'm experiencing the same behavior on a pocophone f1

**Comment by AbedElez** [comment]
The feature isn't finished yet.
