### ISSUE TITLE
Failed connect to proxy server

### ISSUE THREAD

**Issue by enggaraziz** [proxidize/proxidize-android#10]
anyone having issue with latest version? couldn't press the connect button?
it says _Not connected. Restart app and connect again_

here my tested on Redmi Note 3 & Redmi 8 

https://user-images.githubusercontent.com/7285051/197627631-1b66cd29-4784-4e10-8223-86f684d44352.mp4

**Comment by AbedElez** [comment]
Please confirm:
1. Your Android version
2. Location
3. What happens when you select a specific server?

**Comment by AbedElez** [comment]
I'm marking this as enhancement since I can't replicate it

**Comment by enggaraziz** [comment]
1, Redmi Note 3 Android Version 6 & Redmi 8 Android 10
2. Indonesia
3. Its specific Asian Server

**Comment by enggaraziz** [comment]
Its Asia Server issue i think, Temporary solution is change another server such as Middle East, now working well!

**Comment by AbedElez** [comment]
Issue fixed. I'll be setting up some monitoring on the servers to prevent this.
