### ISSUE TITLE
error while connecting 

### ISSUE THREAD

**Issue by A7medBasha2** [proxidize/proxidize-android#102]
hello, i have downloaded your app Proxidize Android Legacy to create my own 4g proxy but every time i press connect it says "Not connected, restart the app and try again " may i know why?
![d8d07241-d852-4ae9-af2f-97c2c9a9dd0d](https://github.com/proxidize/proxidize-android/assets/109818599/a306fd49-f7fe-4896-ab01-4b380263bb4d)
![f8c28105-fd86-45d4-8d27-b0131c949a45](https://github.com/proxidize/proxidize-android/assets/109818599/9004b4d9-c359-4ff7-8318-a43eac8269f7)

**Comment by AbedElez** [comment]
We were running some maintenance on the servers. Should be all good now.

Keeping this open for now as a reference.

**Comment by ShahoBag** [comment]
Hello there. I set up my own server but connecting is problematic. I get the same error. Can the server location effect the possibility of successful connection?

**Comment by ShahoBag** [comment]
> Hello there. I set up my own server but connecting is problematic. I get the same error. Can the server location effect the possibility of successful connection?

I solved the problem. For you guys using your own server (Which is much better in speed) try to change the port multiple times. I don't why but 2000 didn't work and https (443) got working without any problems.

**Comment by ShahoBag** [comment]
I use port "443".On the phone I can see that it is connected and I get "connection successful" message. However I cannot connect to the proxy nor change the ip using API.

**Comment by ShahoBag** [comment]
I have set up my own server and I get "connection successful" on my phones. However I can't connect to the proxies nor change the IP using API.

Do we need to do modifications to our server?

**Comment by JohnnyOmm** [comment]
> I have set up my own server and I get "connection successful" on my phones. However I can't connect to the proxies nor change the IP using API.
> 
> Do we need to do modifications to our server?

im getting this error as well! I even opened up the port on my ubuntu server and still cant connect. I have tmobile

**Comment by AbedElez** [comment]
> I have set up my own server and I get "connection successful" on my phones. However I can't connect to the proxies nor change the IP using API.

Does the app show as connected? Where is the server hosted?

**Comment by ShahoBag** [comment]
> > I have set up my own server and I get "connection successful" on my phones. However I can't connect to the proxies nor change the IP using API.
> 
> Does the app show as connected? Where is the server hosted?

Yes the app shows "connection success" and I get the ports and username and password. The server is hosted in Iran.
I tried changing the DNS, too. Tried 8.8.8.8 and 1.1.1.2, still no results.

**Comment by dimon66682** [comment]
Is there a way for the developer to solve this problem or is this a paid service?

**Comment by ShahoBag** [comment]
> > > I have set up my own server and I get "connection successful" on my phones. However I can't connect to the proxies nor change the IP using API.
> > 
> > 
> > Does the app show as connected? Where is the server hosted?
> 
> Yes the app shows "connection success" and I get the ports and username and password. The server is hosted in Iran. I tried changing the DNS, too. Tried 8.8.8.8 and 1.1.1.2, still no results.

I tried two other servers in Germany and Turkey from two different datacenters. The same problem remains unfortunately. I appreciate it that you made this awesome application opensource and free. I hope you can solve this problem. Thank you @AbedElezz.

**Comment by dimon66682** [comment]
> > > > Я настроил свой собственный сервер и на своих телефонах получаю «соединение успешное». Однако я не могу подключиться к прокси-серверам и изменить IP-адрес с помощью API.
> > > 
> > > 
> > > Приложение отображается как подключенное? Где размещен сервер?
> > 
> > 
> > Да, приложение показывает «успешное подключение», и я получаю порты, имя пользователя и пароль. Сервер расположен в Иране. Я тоже пробовал менять DNS. Пробовал 8.8.8.8 и 1.1.1.2, все равно результатов нет.
> 
> Я попробовал два других сервера в Германии и Турции из двух разных центров обработки данных. К сожалению, та же проблема остается. Я ценю, что вы сделали это замечательное приложение открытым и бесплатным. Я надеюсь, что вы сможете решить эту проблему. Спасибо@AbedElezz.

Have you opened ports 10000-60000?

**Comment by ShahoBag** [comment]
> > > > > Я настроил свой собственный сервер и на своих телефонах получаю «соединение успешное». Однако я не могу подключиться к прокси-серверам и изменить IP-адрес с помощью API.
> > > > 
> > > > 
> > > > Приложение отображается как подключенное? Где размещен сервер?
> > > 
> > > 
> > > Да, приложение показывает «успешное подключение», и я получаю порты, имя пользователя и пароль. Сервер расположен в Иране. Я тоже пробовал менять DNS. Пробовал 8.8.8.8 и 1.1.1.2, все равно результатов нет.
> > 
> > 
> > Я попробовал два других сервера в Германии и Турции из двух разных центров обработки данных. К сожалению, та же проблема остается. Я ценю, что вы сделали это замечательное приложение открытым и бесплатным. Я надеюсь, что вы сможете решить эту проблему. Спасибо@AbedElezz.
> 
> Have you opened ports 10000-60000?

I just did. Still no results.

**Comment by ShahoBag** [comment]
> > > > > Я настроил свой собственный сервер и на своих телефонах получаю «соединение успешное». Однако я не могу подключиться к прокси-серверам и изменить IP-адрес с помощью API.
> > > > 
> > > > 
> > > > Приложение отображается как подключенное? Где размещен сервер?
> > > 
> > > 
> > > Да, приложение показывает «успешное подключение», и я получаю порты, имя пользователя и пароль. Сервер расположен в Иране. Я тоже пробовал менять DNS. Пробовал 8.8.8.8 и 1.1.1.2, все равно результатов нет.
> > 
> > 
> > Я попробовал два других сервера в Германии и Турции из двух разных центров обработки данных. К сожалению, та же проблема остается. Я ценю, что вы сделали это замечательное приложение открытым и бесплатным. Я надеюсь, что вы сможете решить эту проблему. Спасибо@AbedElezz.
> 
> Have you opened ports 10000-60000?

Do you have firewall on your server?

**Comment by ShahoBag** [comment]
> > > > > Я настроил свой собственный сервер и на своих телефонах получаю «соединение успешное». Однако я не могу подключиться к прокси-серверам и изменить IP-адрес с помощью API.
> > > > 
> > > > 
> > > > Приложение отображается как подключенное? Где размещен сервер?
> > > 
> > > 
> > > Да, приложение показывает «успешное подключение», и я получаю порты, имя пользователя и пароль. Сервер расположен в Иране. Я тоже пробовал менять DNS. Пробовал 8.8.8.8 и 1.1.1.2, все равно результатов нет.
> > 
> > 
> > Я попробовал два других сервера в Германии и Турции из двух разных центров обработки данных. К сожалению, та же проблема остается. Я ценю, что вы сделали это замечательное приложение открытым и бесплатным. Я надеюсь, что вы сможете решить эту проблему. Спасибо@AbedElezz.
> 
> Have you opened ports 10000-60000?

Where is your server located?

**Comment by ShahoBag** [comment]
By the way the default servers on the app work fine just very low speed. So I don't think the problem would be my location. Even the API works fine right now. The output of "iptables -S" is 
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
Everything is permitted.

**Comment by ShahoBag** [comment]
The app and the script work perfectly fine. My problem was server side. Some companies and datacenters have special limitations, so that you can't use the server as a proxy server.

Anyways I think it is better to add these comments to README file:
1) First of all the server will probably deny performing the "setsid" command. So maybe add the "chmod +x ./server/server" before that.
2) Next it is better to have firewall enabled. permitting forwarding using "ufw default allow FORWARD" command and then opening 2000 and 10000:60000 both tcp and udp. 
3) Finally you are good to go for the "setsid" command and the proxy will work perfectly.

Thank you again @AbedElezz @YamenAlazzam1

**Comment by charlescee20** [comment]
This issue has appeared again. Is maintenance going on?

**Comment by ShahoBag** [comment]
> This issue has appeared again. Is maintenance going on?

appeared indeed. Sometimes connecting sometimes not.
