### ISSUE TITLE
Socks5 Test Failed on Proxifier

### ISSUE THREAD

**Issue by Cowcaz** [proxidize/proxidize-android#104]
Hey guys, hope you're all doing well. 

I'm having a little issue with the application. I'm hosting custom proxies, and on some phones, the SOCKS5 tests pass, and I can use them. But on others, they fail, and I can't browse the internet with these proxies. I can only configure them on Mozilla.

Anyone got a solution? Thanks in advance!

![ffff](https://github.com/proxidize/proxidize-android/assets/163605633/fa65e8a6-2eef-477e-b041-75efe47d655f)

**Comment by AbedElez** [comment]
Can you share which models work and which don't?
