### ISSUE TITLE
low speed even on own server?

### ISSUE THREAD

**Issue by g0ldyy** [proxidize/proxidize-android#105]
Hello,
I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?

**Comment by g0ldyy** [comment]
maybe it would be good to add wifi split feature too 😅?

**Comment by g0ldyy** [comment]
I heard about a new project from you that is much more optimized but it has already been several months 👌

**Comment by pauloswear** [comment]
I guess that i'ts something related to their tunnel

-- edit

I can confirm, even using my own server it does not take up than 50mb/s (800MB/s of network bandwidth)

**Comment by g0ldyy** [comment]
> I guess that i'ts something related to their tunnel
> 
> -- edit
> 
> I can confirm, even using my own server it does not take up than 50mb/s (800MB/s of network bandwidth)

do you know any alternative to get good speed?

**Comment by pauloswear** [comment]
I'm not the right person to tell it, maybe @YamenAlazzam1, @AbedElezz  can tell us.
My guess that's tunneling server application that contains some bandwidth limitation.
Here even if I upgrade my server has 1500MBP/s UP and DOWN i can't reach more than 50MB, so definitly nothing in our control.


/server/server it's a binary, we do not have source code from it, so... 


"
Low speeds. Since both incoming and outgoing connections are passing through the same network interface, the speed you get will be a fifth of the mobile speed.
"

They say that network speed is affected cause incoming and outcoming packages travel in same network interface, but I guess not. In windows OS we have the adapter and out and in traffic pass through the same and speed it's not affected too much.

**Comment by dimon66682** [comment]
Подскажите как настроить собственный сервер на Ubuntu , по инструкции что написано не согласуеться с приложением. Даже с открытыми портами на сервере. Буду очень блогадарен за помощь.

**Comment by AbedElez** [comment]
The limitation, if existing, likely comes from the tunneling server we use https://github.com/fatedier/frp -- you can check their repo and let us know if you find anything @g0ldyy @pauloswear

**Comment by pauloswear** [comment]
> The limitation, if existing, likely comes from the tunneling server we use https://github.com/fatedier/frp -- you can check their repo and let us know if you find anything @g0ldyy @pauloswear

I've already expected that slow network comes from tunneling server..

--

https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml

```
# Limit bandwidth for this proxy, unit is KB and MB
**transport.bandwidthLimit = "1MB"**

# Where to limit bandwidth, can be 'client' or 'server', default is 'client'
transport.bandwidthLimitMode = "client"
```

Are we able to edit this options ? 
I see here that server contains some little modifications to give to server.ini some basic configurations. 


Maybe directly give option to use ssh tunneling can be a good alternative.

**Comment by AbedElez** [comment]
Closed due to low effort contributions. Please open a new issue after you read the documentation and are ready to make high-quality contributions.

**Comment by g0ldyy** [comment]
ridiculous

**Comment by g0ldyy** [comment]
ridiculous.

**Comment by ShahoBag** [comment]
> Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?

When did you manage to setup your own server?

**Comment by g0ldyy** [comment]
> > Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?
> 
> When did you manage to setup your own server?

wdym, I set it up a few days ago following the instructions given by Proxidize.

**Comment by ShahoBag** [comment]
> > > Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?
> > 
> > 
> > When did you manage to setup your own server?
> 
> wdym, I set it up a few days ago following the instructions given by Proxidize.

Where is your server located? Did you use the port "2000"?

**Comment by g0ldyy** [comment]
> > > > Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?
> > > 
> > > 
> > > When did you manage to setup your own server?
> > 
> > 
> > wdym, I set it up a few days ago following the instructions given by Proxidize.
> 
> Where is your server located? Did you use the port "2000"?

yes, the proxy is working fine, it's just slow asf

**Comment by ShahoBag** [comment]
> > > > > Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?
> > > > 
> > > > 
> > > > When did you manage to setup your own server?
> > > 
> > > 
> > > wdym, I set it up a few days ago following the instructions given by Proxidize.
> > 
> > 
> > Where is your server located? Did you use the port "2000"?
> 
> yes, the proxy is working fine, it's just slow asf

Did you try changing the ip using API? Did API work fine?

**Comment by g0ldyy** [comment]
> > > > > > Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?
> > > > > 
> > > > > 
> > > > > When did you manage to setup your own server?
> > > > 
> > > > 
> > > > wdym, I set it up a few days ago following the instructions given by Proxidize.
> > > 
> > > 
> > > Where is your server located? Did you use the port "2000"?
> > 
> > 
> > yes, the proxy is working fine, it's just slow asf
> 
> Did you try changing the ip using API? Did API work fine?

yes of course, everything is working fine, just very low speed

**Comment by Anaski99** [comment]
> > > > > > > Hello, I just setup my own server and I get pretty much exactly the same speed as the public servers (~160ms)... Is it normal?
> > > > > > 
> > > > > > 
> > > > > > When did you manage to setup your own server?
> > > > > 
> > > > > 
> > > > > wdym, I set it up a few days ago following the instructions given by Proxidize.
> > > > 
> > > > 
> > > > Where is your server located? Did you use the port "2000"?
> > > 
> > > 
> > > yes, the proxy is working fine, it's just slow asf
> > 
> > 
> > Did you try changing the ip using API? Did API work fine?
> 
> yes of course, everything is working fine, just very low speed

Did you manage to resolve that slow speed ? did you try to use frp as suggested ?
