### ISSUE TITLE
Server is not open source

### ISSUE THREAD

**Issue by flikites** [proxidize/proxidize-android#11]
Server file is binary, can't actually tell what it is doing.

Please open source the server file!

**Comment by AbedElez** [comment]
Check the credits. It's a standard FRP server.

**Comment by flikites** [comment]
Thanks. I'm gonna deploy the server using the code from this repo:

https://github.com/fatedier/frp

Thanks for pointing out the credits.

Curious as to why you needed to make the server file output in binary?

**Comment by AbedElez** [comment]
> Curious as to why you needed to make the server file output in binary?

Which output?

**Comment by flikites** [comment]
This file: 
https://github.com/proxidize/proxidize-android/blob/main/server/server

**Comment by AbedElez** [comment]
Are you asking why did I put the binary in the repo?

**Comment by flikites** [comment]
I'm asking why no one can verify the contents of the server file I linked to.  ---- On Wed, 26 Oct 2022 17:30:33 -0400  ***@***.***  wrote ----
Are you asking why did I put the binary in the repo?

**Comment by AbedElez** [comment]
If you spend 5 seconds reading the repo you will understand. It's a standard server.
