### ISSUE TITLE
Does it take the IP Address of Tunnelling Server?

### ISSUE THREAD

**Issue by kj2222** [proxidize/proxidize-android#111]
So the expected behaviour when we click connect should be: if the mobile is connected to wifi, then the proxy needs to show the IP address of the Wifi network?

But even though I'm located in country A, the proxy IP address is of country B. This is because it seems to be taking the IP address of the tunnelling server?

**Comment by AbedElez** [comment]
Refer to the diagram: https://github.com/proxidize/proxidize-android?tab=readme-ov-file#table-of-contents

The IP address you see in the proxy is the tunneling server IP. You can check the real IP by connecting to the proxy and loading a website like https://eth0.me or https://proxy.bot
