### ISSUE TITLE
The app won't install on Pixel 8 (android 14)

### ISSUE THREAD

**Issue by Platoshka-cmd** [proxidize/proxidize-android#112]
Hello! When installing the application, the message "Application not installed" appears.
I tried to solve this problem myself, but I couldn’t solve it.
![photo_2024-06-08_02-46-56](https://github.com/proxidize/proxidize-android/assets/116262469/8ac99990-e8a4-4b52-9d5d-cc6e55a5019e)

**Comment by AbedElez** [comment]
What's the phone model and Android version? A screenshot from the software information tab on the phone would be appreciated. (Make sure to cover any sensitive information.)

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by Platoshka-cmd** [comment]
> Какая модель телефона и версия Android? Буду признателен за снимок экрана с вкладки информации о программном обеспечении на телефоне. (Обязательно скройте любую конфиденциальную информацию.)
My phone model is Google Pixel 8, Android 14 version
