### ISSUE TITLE
The IP change does not work on one of the devices. 

### ISSUE THREAD

**Issue by xdriver666** [proxidize/proxidize-android#12]
You can see in the screen when you click on the plane, but the network is not disconnected and the IP does not change.
Phone model: TP-Link TP801A
Android 6.0.1
The phone is rooted.
I have several devices on different versions of Android. On Android 7 the IP change works on all devices, but on Android 6 none. 

Can you add an option to your application so that, if you have root, it switches without a helper?

**Comment by AbedElez** [comment]
Closing this until I start working on it again soon.
