### ISSUE TITLE
wi-fi backend and fingerprint are not working.

### ISSUE THREAD

**Issue by snorlax1998** [proxidize/proxidize-android#15]
Hello, everything works great, but the wi-fi backend and typos do not work. When I click on these functions, the message "Changes saved, please restart the app" appears. After the reboot, nothing turns on and everything returns as it was. The switch is in the inactive position.
the fingerprint doesn't change 
![photo_2022-11-12_12-06-21](https://user-images.githubusercontent.com/64140355/201467181-cd75b526-53aa-4506-9597-24d5a835f99a.jpg)
![photo_2022-11-12_12-06-23](https://user-images.githubusercontent.com/64140355/201467184-65076de0-d1e5-4790-8cb4-2ab35970ff70.jpg)

**Comment by AbedElez** [comment]
These are still very experimental and not fully implemented. Should be improved with the next update.

**Comment by snorlax1998** [comment]
Hello, can I somehow communicate with you personally? in telegrams. I wanted to show you a ready-made program that has these functions and even more. It will be useful for you.   Can you write to me https://t.me/decomarketru

**Comment by AbedElez** [comment]
Closing this for now until I start working on it again.

**Comment by TheGP** [comment]
> These are still very experimental and not fully implemented.

What did you mean by that? Did it work on only specific device? Did it require root? Sad that you dropped the feature.
