### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by olorus** [proxidize/proxidize-android#16]
Hello

It looks like Proxidize servers banned IPs from ISP Euro-Information Technologies

One of the IPs: 193.57.125.15

It's a legit 4G from a real phone mobile company. I know ipqualityscore report them a potential fraud but there are true customers like me.

Can you unban?

**Comment by AbedElez** [comment]
Can you post a screenshot of the error you got? What makes you think the IPs are banned?

**Comment by olorus** [comment]
because I switch sim card or use wifi to change IP and it connects.

**Comment by AbedElez** [comment]
I see. Where are you based and what is the carrier? I'll review the firewall rules on the server soon.

**Comment by olorus** [comment]
France, NRJ Mobile

**Comment by AbedElez** [comment]
All the servers are using the default provider's firewall rules. Not sure I wanna play with those now. Have you tried deploying your own server? https://github.com/proxidize/proxidize-android#deploying-your-own-server

**Comment by AbedElez** [comment]
Closing this for now. Feel free to ping me if you find anything new.
