### ISSUE TITLE
IP change does not work

### ISSUE THREAD

**Issue by waterproxy1** [proxidize/proxidize-android#17]
Hey! I tried using the IP change manually and by the API link.
It shows airplane mode activate for a split second, then disables it.
The IP remains the same.
Airplane mode should remain enabled for at least 5+ seconds for the IP to actually change.
Please fix this asap!

**Comment by AbedElez** [comment]
Can you make a video demonstration showing the IP changing and not changing?

**Comment by glasedip** [comment]
Hi I know this issue, it's to fast air plane switch, you have to pause 3 seconds minimum between activate air plane and deactivate it to see ip change. Personnaly  I use macrodroid apk to set this up and it's working well. Hope it helps.

**Comment by waterproxy1** [comment]
> 

Hey! Could you please explain how the macrodroid is setup?
Macrodroid works with the proxidize api link for manual rotation?
Please let me know!

**Comment by waterproxy1** [comment]
> Hi I know this issue, it's to fast air plane switch, you have to pause 3 seconds minimum between activate air plane and deactivate it to see ip change. Personnaly I use macrodroid apk to set this up and it's working well. Hope it helps.

Hey! Could you please explain how the macrodroid is setup?
Macrodroid works with the proxidize api link for manual rotation?
Please let me know!

**Comment by waterproxy1** [comment]
> Can you make a video demonstration showing the IP changing and not changing?

https://user-images.githubusercontent.com/118281825/202240784-0771cb46-463a-44b8-b070-d9c3b519a373.MOV

As you can see, some devices need airplane mode activated for a longer duration for the network reset to happen, if not, the IP will remain the same.

**Comment by glasedip** [comment]
Here is a short video tuto. As you can see at the end I touch flottant button and airplane mode switch with the 3 seconds delay, it's not as fast as proxifier so it's a good alternative for now ;) hope it helps. Video file link : 
https://files.fm/u/nvmvs274b

**Comment by waterproxy1** [comment]
> Here is a short video tuto. As you can see at the end I touch flottant button and airplane mode switch with the 3 seconds delay, it's not as fast as proxifier so it's a good alternative for now ;) hope it helps. Video file link : https://files.fm/u/nvmvs274b

Thank you for the reply!
This definitely works, but i want to be able to use Proxidize's api link to manually rotate.

**Comment by AbedElez** [comment]
Thanks for that. I'll be taking a look shortly.

**Comment by waterproxy1** [comment]
> Thanks for that. I'll be taking a look shortly.

Sounds good. Thank you!

**Comment by glasedip** [comment]
welcome ;))

**Comment by AbedElez** [comment]
@waterproxy1 Fixed with v2.1.1 https://github.com/proxidize/proxidize-android/releases/tag/v2.1.1 test it and let me know if it works.
