### ISSUE TITLE
Can't deploy server

### ISSUE THREAD

**Issue by waterproxy1** [proxidize/proxidize-android#18]
Hey guys!
I'm having trouble deploying Proxidize android onto my Ubuntu server. 
When I run the command to start the server, it says "no directory found."

![image](https://user-images.githubusercontent.com/118281825/202711268-cdcbe6ad-97fe-4f0c-a111-fd0b97b0a2a8.jpeg)

![image](https://user-images.githubusercontent.com/118281825/202710731-8dc3a222-0c19-4f6a-9a29-1e853c9acbd1.jpeg)

I tried doing "cd ./server" but even then it's still saying no directory found.

Please help me out here, as I really want to get this deployed asap!

**Comment by glasedip** [comment]
hi, run these commands one by one to run the server (you need to access directory first)
1. cd proxidize-android
2. cd ./server
4. chmod +x ./server
3. setsid ./server -c ./server.ini &

hope it helps ;)

**Comment by glasedip** [comment]
assuming you edited "server.ini" file

**Comment by waterproxy1** [comment]
> hi, run these commands one by one to run the server (you need to access directory first)
> 
> 1. cd proxidize-android
> 
> 2. cd ./server
> 
> 4. chmod +x ./server
> 
> 3. setsid ./server -c ./server.ini &
> 
> 
> 
> hope it helps ;)

Thank you! 
I ran the commands and it said my host is 0.0.0.0
Is that normal? Just making sure.

![image](https://user-images.githubusercontent.com/118281825/202773883-25b95885-14b1-4a56-9ff5-6c505ec63e6c.jpeg)

I tried testing the proxy out, but nothing connects unfortunately. Maybe I did something wrong?

**Comment by waterproxy1** [comment]
I was able to connect within the Proxidize app.
But the proxy itself doesn't work or connect at all. 

![image](https://user-images.githubusercontent.com/118281825/202780945-b671346f-4a47-496e-8d43-de59360a4ce7.jpeg)

**Comment by glasedip** [comment]
ok type commande line bellow to see your server IP adress and put that IP into proxidize app hostname configuration (and port of course)

hostname -I

hostname MUST be an IP adress or server URL such as "example.name.com" (not "0.0.0.0" or "hostname" or "server1", "server2" etc...)
hope you see what i mean.

let me know.

**Comment by glasedip** [comment]
its normal when you run server and you see in blue "listen on 0.0.0.0:2000", don't worry about that, same for me and all of us i suppose...

But you have to run command line "hostname -I" to check and see your server IP adress you running on.

**Comment by WesleyMarinho** [comment]
Here I've tried everything, I can't connect to my server... Did it work for you?

**Comment by snorlax1998** [comment]
Have you opened ports for the router?

**Comment by WesleyMarinho** [comment]
> Have you opened ports for the router?

It really was the door, but how can I get past it... I use csf, when activating it it is blocking and the door is already open

**Comment by snorlax1998** [comment]
We won't be able to help you open the ports. You have to do it yourself on your servers. Since the method depends on the equipment.

**Comment by AbedElez** [comment]
@waterproxy1 Which host is this server on? If it's any of the cloud providers, you'll need to open the ports. Look for your host's documentation.

**Comment by oloho** [comment]
I can't connect to my proxies on my own server, how to do?

In the android app, it can connect to my own server, but when I try to connect to the generated proxy, I can't connect.
How to know the reason?

I use contabo VPS, if anyone know how to configure... help I have install everything but I just can't connect to proxies

I use these commands in ssh
ufw allow 1000:60000/tcp
ufw allow 1000:60000/udp

Am I doing it right?

**Comment by AbedElez** [comment]
What's the output of `iptables -S` on your server?

**Comment by oloho** [comment]
in fact in contabo I succeed to connect to my proxy, I had to kill process 
sudo kill `sudo lsof -t -i:2000`

but I bought another server and I can't connect, proxidize app says "not connected, try again later, restart"

I have to idea where I got wrong there

**Comment by oloho** [comment]
ok now I change sim and the app now allow to connect to my custom server
in fact it's weird
my IP cause the same problem with Proxidize server and I opened a topic a time ago
https://github.com/proxidize/proxidize-android/issues/16

Why my carrier is not supported either by my own server and Proxidze one?

**Comment by AbedElez** [comment]
@oloho whats the output of `sudo iptables -S` on your server?

**Comment by oloho** [comment]
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

**Comment by AbedElez** [comment]
Completely open. It's something with your mobile provider. I think they might have some DPI process that blocks proxies.

Where are you based? Are VPNs banned in your country?

**Comment by oloho** [comment]
France. How can they know it's a proxy?

**Comment by AbedElez** [comment]
Some countries like Egypt or Iran ban VPNs by doing a MITM and DPI to see the actual packets. I don't think this would happen in France though.

Which carrier is this?

**Comment by oloho** [comment]
NRJ mobile.
I can connect to a VPN and use a proxy but not generate proxies.

**Comment by ghost** [comment]
Can i add multiple token value in server.ini ?

**Comment by sansopheakh** [comment]
> NRJ mobile. I can connect to a VPN and use a proxy but not generate proxies.

Chat to my Facebook.
I will help you config this.
https://web.facebook.com/pheakh.teay/

**Comment by blesseco** [comment]
i have able to start on server custom server also connected to that in app but link of change ip and proxy not working server aws i think port block because its random 
can you fix ports and open them in aws
if i am wrong can you please tell me how to make proxy and link working

![image](https://github.com/proxidize/proxidize-android/assets/136700016/ca6907f2-5294-44a2-a8db-95ec08170c11)

![image](https://github.com/proxidize/proxidize-android/assets/136700016/2256b03f-8d32-4b1d-88ff-475d1eeba1de)

**Comment by blesseco** [comment]
solved need to open range of port
if you can tell me fixed port that will be nice
