### ISSUE TITLE
I encountered a problem. When I used the username and password to connect to the proxy, the connection failed. When I only used the ip address and port to connect, the connection succeeded

### ISSUE THREAD

**Issue by zhanghoufeng** [proxidize/proxidize-android#20]

**Comment by zhanghoufeng** [comment]
How to solve this problem

**Comment by zhanghoufeng** [comment]
Do I need to configure the proxy username and password on the server side

**Comment by AbedElez** [comment]
Please make a video demonstrating the issue. If I understood correctly, accessing the proxy without the credentials wouldn't be possible unless it's cached.

Usually credentials are cached for 60 seconds per connection, though I don't think this is what's happening here.

**Comment by zhanghoufeng** [comment]
https://user-images.githubusercontent.com/119011747/203860665-474f3535-27f4-4302-a94c-3ed5353f6a39.mp4

**Comment by zhanghoufeng** [comment]
Please help me check, I have sent the video

**Comment by zhanghoufeng** [comment]
Do I want to set something up on the server, because I'm using an http connection and I've got a user name and a password, and it says the connection is successful, but with socks5, it's not going to work

**Comment by snorlax1998** [comment]
socks5 doesn't work for me either, but http does

**Comment by AbedElez** [comment]
What ports do you have open on your server?

**Comment by AbedElez** [comment]
Closing due to no response
