### ISSUE TITLE
Can't connect ! Please support !

### ISSUE THREAD

**Issue by hoangthangbk51** [proxidize/proxidize-android#24]
Dear sir. This app very nice and it help me alot .But today i have problem can't conect. 
I reset app many time but still the same . 
Please check on the image 
![1](https://user-images.githubusercontent.com/77531950/205476323-c72cec4a-179d-4ff5-aed5-b5c723427734.png)

**Comment by AbedElez** [comment]
@hoangthangbk51 Exit the app and try now. The Asia server was fully loaded.

There are thousands of devices using the default servers, so consider deploying your own.

**Comment by hoangthangbk51** [comment]
Thanks you somuch. Run back. With out knowledge about making servers. Hard to me make my own server.

**Comment by ghost** [comment]
> @hoangthangbk51 Exit the app and try now. The Asia server was fully loaded.
> 
> There are thousands of devices using the default servers, so consider deploying your own.

I have tested all your default server and also use my own server. It's still not work.
It's show Connected but it's not work.

**Comment by AbedElez** [comment]
@sansopheakh Open a new issue with a full description of what's happening and the error you're getting.
