### ISSUE TITLE
The app shuts down after some use.

### ISSUE THREAD

**Issue by snorlax1998** [proxidize/proxidize-android#28]
The app shuts down after some use. Everything is fine, but after some use of the application, it turns off. You need to reopen the application and connect. I tried it on 2 galaxy s8 and pocophone phones . Without root . I would understand why. What could be the problem? I'm connecting to your servers.

**Comment by waterproxy1** [comment]
Servers are over crowded, so my guess is, your proxy gets disconnected for make space for others.
Same thing is happening to me. Best to create your own server.

**Comment by AbedElez** [comment]
Do you still see the notification in your notifications bar? If not, your phone is closing the app, and you need to check your battery optimization settings.
