### ISSUE TITLE
How to use Proxy without Username/Password ?

### ISSUE THREAD

**Issue by eakteam** [proxidize/proxidize-android#29]
The proxy server seems to works fine, but how to use Proxy Server without authentication ?

**Comment by AbedElez** [comment]
Trying to run the proxy without authentication will get your proxy in the hands of malicious actors in less than 5 minutes and will be a massive security issue. This would never be added, though I might add IP authentication later on.

**Comment by eakteam** [comment]
But, nobody can know my proxy server IP on local network, or without knowing the port to connect.

**Comment by AbedElez** [comment]
That's not how this app works. Every proxy will be open to the internet. Make sure you read the documentation.
