### ISSUE TITLE
Deployed server, but proxy dosen't connect

### ISSUE THREAD

**Issue by waterproxy1** [proxidize/proxidize-android#31]
Hey everyone!
I previously was having trouble with deploying my own server with proxidize, but I managed to successfully deploy the server.
I got the Ipv4 address of the server, and added it into my Router gateway.
The proxidize app is able to generate the proxy using my public IP address, but the proxy itself will not connect at all.
![image](https://user-images.githubusercontent.com/118281825/207410754-aa52669a-4d3e-4a8e-a410-d2ef8d378fca.png)
This image shows the ports of the server, which in this case is 2000, as that was suggested in the instructions.
Is the port supposed to be 2000 for all boxes, and is it supposed to be TCP/UDP?
![image](https://user-images.githubusercontent.com/118281825/207411030-67203b70-d7db-427b-9422-998d291bd9b1.png)
I then made sure to add that configuration to my server.
![IMG-0512](https://user-images.githubusercontent.com/118281825/207411586-b6bf321e-fa98-4325-a1c4-3e66de76ac09.jpg)
I then used my public IP and the port 2000 to connect to my server in the proxidize app.
As you can see, the app itself shows that the proxy works.
![image](https://user-images.githubusercontent.com/118281825/207419107-8667a6ee-1300-49c2-86e0-a95c2eb3ea4d.png)
But as you can see here, there is no connection.
So what is the issue? Am I using the wrong port for portfowarding my server?
Please let me know asap!

**Comment by sergopng** [comment]
You also need to open a port for 51523 or 29161

**Comment by waterproxy1** [comment]
> 

![image](https://user-images.githubusercontent.com/118281825/207453472-b85a517c-e977-4b7b-b93f-f879eda7e864.png)
Like this?

**Comment by sergopng** [comment]
Yes, try the connection

**Comment by waterproxy1** [comment]
![image](https://user-images.githubusercontent.com/118281825/207459748-0c39defb-cc0e-45c7-bf99-23bc80ac2768.png)
![IMG-0513](https://user-images.githubusercontent.com/118281825/207460237-433df4ee-8239-4b48-87e5-1a3c6f088d82.jpg)
Okay so I opened the ports 15000-20000 but proxy still dosent connect.
I feel like im missing something obvious.

**Comment by waterproxy1** [comment]
> Yes, try the connection

![image](https://user-images.githubusercontent.com/118281825/207460432-bd011c79-93de-4163-a063-1bceabbf53ca.png)
![IMG-0513](https://user-images.githubusercontent.com/118281825/207460443-fad3033f-4a87-47de-80c0-1338670585c6.jpg)
I opened ports 15000-25000 but proxy still doesn't connect.
I feel like im missing something obvious haha

**Comment by sergopng** [comment]
> > Да, попробуйте подключить
> 
> ![изображение](https://user-images.githubusercontent.com/118281825/207460432-bd011c79-93de-4163-a063-1bceabbf53ca.png) ![IMG-0513](https://user-images.githubusercontent.com/118281825/207460443-fad3033f-4a87-47de-80c0-1338670585c6.jpg) Я открыл порты 15000-25000, но прокси все равно не подключается. Я полагаю, что упускаю что-то очевидное, ха-ха

Hmm, maybe I forgot something too, well actually I did easier, I rented a vds with ubuntu for 3$ per month, works great

**Comment by waterproxy1** [comment]
![IMG-0514](https://user-images.githubusercontent.com/118281825/207643430-33361937-8115-45b1-8027-2bee0b131416.jpg)
I went to check back on my server, and this is what the terminal is showing.
I'm assuming these error messages are whenever I tried to connect with one of my devices.
If anyone knows how to fix this, please let me know.

**Comment by waterproxy1** [comment]
> Hmm, maybe I forgot something too, well actually I did easier, I rented a vds with ubuntu for 3$ per month, works great

Which VDS did you choose? Might be easier for me.

**Comment by AbedElez** [comment]
@waterproxy1 Where is this server located?

Just get a VPS from DigitalOcean or Hetzner if you're having issues with the ports.

**Comment by waterproxy1** [comment]
> @waterproxy1 Where is this server located?
> 
> Just get a VPS from DigitalOcean or Hetzner if you're having issues with the ports.

Hey! 
This is my own personal server connecting directly into my modem via ethernet.
I have other servers setup here as well.
If I'm unable to figure this out I'll definitely go with a vps

**Comment by AbedElez** [comment]
This would depend on your network typography. The server and proxy ports need to be accessible from the web in order for everything to function correctly.

**Comment by waterproxy1** [comment]
> This would depend on your network typography. The server and proxy ports need to be accessible from the web in order for everything to function correctly.
![1](https://user-images.githubusercontent.com/118281825/207685099-bde406be-eeae-41a2-b74d-d5e0411e5f24.jpg)

![2](https://user-images.githubusercontent.com/118281825/207685108-f2f5fffe-d17a-4b63-9726-5e9147e02172.jpg)

I just purchased a vps from Digital Ocean, and im still getting the same problem.
Right when I press connect on Proxidize, it says "authorization failed" on the vps console.
It shows that it connects in the proxidize app, but proxy dosent work.

**Comment by waterproxy1** [comment]
Wait! I figured it out.
The issue was the server.ini file.
For some reason, I didnt put the correct token.
