### ISSUE TITLE
Some phones can't connect to custom server!

### ISSUE THREAD

**Issue by waterproxy1** [proxidize/proxidize-android#33]
Hey guys!
So a few of my devices are pixel 3A's and they are unable to connect to my custom server.
Some of my other phones can connect fine, but it seems some just don't work.
Basically when I put the custom server info in and save it, I exit the app and open it but then it switches itself back to "Auto" by itself instead of staying on "custom", causing it to only connect to the Proxidize servers instead of mine. 
What is causing this to happen?

**Comment by waterproxy1** [comment]
I also tried testing with some Samsung phones and still the same issue happens.
If any of you know what's the cause of this, please let me know as this definitely needs to be fixed!

**Comment by sergopng** [comment]
I also thought for a long time how to fix it, came to the fact that I turned on the flight mode and run Proxidize

**Comment by waterproxy1** [comment]
> I also thought for a long time how to fix it, came to the fact that I turned on the flight mode and run Proxidize

I tried doing this, as well as reinstalling the app. Same issue continues.

**Comment by AbedElez** [comment]
Please share the exact models of the phones you're having problems with.

**Comment by waterproxy1** [comment]
> Please share the exact models of the phones you're having problems with. 

Google Pixel 3.
Google pixel 3a
Samsung Galaxy S7
Samsung Galaxy S7 Edge. 

It's strange because I have a few of these models that are currently connecting to the server fine,but any new phones that I get, or phones that I currently have, won't connect.

**Comment by AbedElez** [comment]
So some devices work, and others don't, even though it's the same model? It's possible you're not putting the details correctly. Are all the phones using the same version?

**Comment by waterproxy1** [comment]
> So some devices work, and others don't, even though it's the same model? It's possible you're not putting the details correctly. Are all the phones using the same version?

Yes exactly, it's really confusing.
All phones are using the same version, yes. 
I can send a video demonstration. 
I'll show the server.ini, to show the port and token.
I really want to solve this problem.

**Comment by waterproxy1** [comment]
I created a new vps server to demonstrate that Proxidize android is not working.

![image](https://user-images.githubusercontent.com/118281825/210287601-d945cdc0-a1ff-40a7-9e94-4e2114c78ff4.jpeg)
![image](https://user-images.githubusercontent.com/118281825/210287604-06e03829-d1dd-4e82-8c17-a92f164ab0e4.jpeg)
![image](https://user-images.githubusercontent.com/118281825/210287714-894caaa9-f79e-4a94-9f91-30b5ea0b5310.jpeg)
![image](https://user-images.githubusercontent.com/118281825/210287719-50979115-83d8-4f48-af75-64539164a059.jpeg)

Here's the server info, and as you can see, when trying to connect to my custom server, it auto joins the default servers.
I tried uninstalling and using airplane mode. It's a bit frustrating.
Also not to mention, api link isn't working for many of the devices.

**Comment by AbedElez** [comment]
**For the server:** Your server ports are closed. Likely by the firewall. You'll need to either open select ports of flush it entirely, which I wouldn't recommend.

**For the app not selecting the server:**

Which version of the app are you using?

Do you hit the exit button to close the app and then reopen it after it's fully closed?

**Comment by waterproxy1** [comment]
> **For the server:** Your server ports are closed. Likely by the firewall. You'll need to either open select ports of flush it entirely, which I wouldn't recommend.
> 
> 
> 
> **For the app not selecting the server:**
> 
> 
> 
> Which version of the app are you using?
> 
> 
> 
> Do you hit the exit button to close the app and then reopen it after it's fully closed?
> 
> 

I'm using digital ocean, by default, the ports should be open.
I'm using the latest version of the Proxidize app.
After saving the info, I click exit on the app. Then I reopen the app by clicking on it.

**Comment by AbedElez** [comment]
> I'm using digital ocean, by default, the ports should be open.

Send me an output of the command:

`iptables -S`


And a screenshot of the terminal output after you launch the server.

The server is not accessible and the only possibles explanations are it's either behind a firewall/ports closed or the server daemon didn't start properly.

For the phone, please confirm the exact steps you use to close the app. And please try using the slightly older release to see if you still get the issues.

Furthermore, please don't open duplicate issues.

**Comment by waterproxy1** [comment]
![image](https://user-images.githubusercontent.com/118281825/210289544-e1367fc8-2db0-42fb-832a-a78977ca7914.jpeg)
Here's the iptables ^

![image](https://user-images.githubusercontent.com/118281825/210289548-fc9afa15-eb1f-4103-9308-f27cc25a1163.jpeg)
Here's the terminal ^

**Comment by waterproxy1** [comment]
Quick update.
I created a fresh vps with DigitalOcean, I disabled the firewall.
I was able to get some phones to connect and proxies work with it.
But there are still some phones that refuse to connect to my custom server, they auto connect to the Proxidize servers.
I tried clearing cache, reinstalling the app, using an older version, using airplane mode and restarting the phone. 
None of these options worked.
Funny thing is, the phones that are able to connect are the same models as the ones that can't connect.
The phones that do connect, on the terminal it displays the phone connection was successful etc, so I know the server is setup properly.
Maybe just some phones refuse to connect?
I'd like to get this issue resolved, because once this is resolved, the app will be perfect.
In a bit, I'll post a few pictures of the terminal and record some videos of me trying to connect to my custom server with one of the phones.

**Comment by AbedElez** [comment]
What is happening is one of the following:

1. You are not inserting the custom server details correctly
2. Some phones are different models and behave differently

Please do the following:

1. Launch the server and keep the terminal open. You should see some logs.
2. Insert the details into the app for the custom app, exit, restart and connect again
3. Monitor the terminal logs on the terminal to see what the output is. If the app is connecting, you should see some logs

And let me know what happens.

**Comment by waterproxy1** [comment]
Hey! I recorded everything to demonstrate what happens.
https://youtu.be/gjAkJtuznBE
Here's the video ^

**Comment by waterproxy1** [comment]
> What is happening is one of the following:
> 
> 1. You are not inserting the custom server details correctly
> 2. Some phones are different models and behave differently
> 
> Please do the following:
> 
> 1. Launch the server and keep the terminal open. You should see some logs.
> 2. Insert the details into the app for the custom app, exit, restart and connect again
> 3. Monitor the terminal logs on the terminal to see what the output is. If the app is connecting, you should see some logs
> 
> And let me know what happens.

Hey! I recorded everything to demonstrate what happens.
https://www.youtube.com/watch?v=gjAkJtuznBE
Here's the video ^

**Comment by AbedElez** [comment]
All clear. Thank you for the demonstration @waterproxy1 

This does indeed look like a bug. I will assign one of our engineers to work on it as my schedule is packed.

To confirm, how are these phones different from the ones that worked? Any information you share will be useful as we must reproduce this internally.

**Comment by waterproxy1** [comment]
> All clear. Thank you for the demonstration @waterproxy1 
> 
> 
> 
> This does indeed look like a bug. I will assign one of our engineers to work on it as my schedule is packed.
> 
> 
> 
> To confirm, how are these phones different from the ones that worked? Any information you share will be useful as we must reproduce this internally.
> 
> 

You're welcome!
I'm happy to hear that it's being worked on.


Here's a few pictures of the working Pixel3a
![image](https://user-images.githubusercontent.com/118281825/211108024-7c347755-fb00-4ca8-a10e-8afa9a3afe16.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211108038-758bcf0e-4da9-49c1-bc69-842c148271eb.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211108057-05d5b623-4125-471f-819e-6f9f97102fca.jpeg)

Now here's photos of the Pixel3a that's not working.
![image](https://user-images.githubusercontent.com/118281825/211108115-6fc5f5ca-62cf-4d84-bc85-25f3ea13b380.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211108129-46513345-4084-4db7-a165-fc18eb8d2c36.jpeg)
Note, this phone I currently don't have a sim inside, that's why there's no ip address displayed.


![image](https://user-images.githubusercontent.com/118281825/211108140-c8a8edb3-3d9e-4d9a-8d96-ede57eef927f.jpeg)

If you need anymore info, please ask me anytime. 
I'm always online!

**Comment by AbedElez** [comment]
Noted. Thank you for the clarification. I'll let you know how things go.

**Comment by waterproxy1** [comment]
Sounds like a plan!

**Comment by AbedElez** [comment]
@waterproxy1 Can you please do the following:
1. Remove any unnecessary apps on the phones that might impede the functions of Proxidize Android Legacy.
2. Send me a screenshot of the permissions page for one phone that's not working and another that's working.
3. If you reinstall the app, will the ones working/not working change? As in, is it always the same phones not working?

**Comment by waterproxy1** [comment]
> @waterproxy1 Can you please do the following:
> 
> 1. Remove any unnecessary apps on the phones that might impede the functions of Proxidize Android Legacy.
> 
> 2. Send me a screenshot of the permissions page for one phone that's not working and another that's working.
> 
> 3. If you reinstall the app, will the ones working/not working change? As in, is it always the same phones not working?
> 
> 
![image](https://user-images.githubusercontent.com/118281825/211198122-2d1437ff-7050-4d65-96df-662526f7d14a.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211198138-021287e2-f647-45fb-98ac-0eaba4a09de6.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211198144-34688590-1e5b-4858-8f37-7d6e6fb80f73.jpeg)
The photos above is the working phone, which is a good pixel 3a

![image](https://user-images.githubusercontent.com/118281825/211198185-626af674-7d7e-4dee-bdd3-5e4b49df12e7.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211198194-a1a95b96-eee5-4515-a1f0-c16b42c18470.jpeg)
![image](https://user-images.githubusercontent.com/118281825/211198201-8b7b0c08-e65a-4ed1-bea3-5b6eacb67e02.jpeg)
The images above are the non-working phone, which is a TCL10 5G UW.

Google play protect is off and disabled.
Battery optimization is off.

When reinstalling the app, the working phone still continues to work fine.

When re-installing the app, the non-working phone continues to not work.

**Comment by AbedElez** [comment]
Got it. Thank you. I'll send an experimental APK shortly.

**Comment by AbedElez** [comment]
@waterproxy1 Please try this and let me know: https://transfer.sh/bkiiJN/app-release.apk

It's experimental.

Edit: Please uninstall all previous versions and any other apps that aren't required for the phone before installing this one.

**Comment by waterproxy1** [comment]
> @waterproxy1 Please try this and let me know: https://transfer.sh/bkiiJN/app-release.apk
> 
> It's experimental.
> 
> Edit: Please uninstall all previous versions and any other apps that aren't required for the phone before installing this one.

![image](https://user-images.githubusercontent.com/118281825/211812508-84e0d5d4-674c-46c0-b1a0-10d20ee412a1.png)
Hey bro! The file is not found.
Could you reupload it for me, I'd love to test it out asap!

**Comment by AbedElez** [comment]
Try this https://transfer.sh/MsNtnp/app-release.apk. It's a temporary link.

**Comment by waterproxy1** [comment]
https://user-images.githubusercontent.com/118281825/211838812-0375e440-a570-4eed-bf79-30c17ac2ca40.mp4

Here's an update. Still the same issue unfortunately. Automatically goes to proxidize servers.
Made sure to recheck the vps server, and can confirm its online and console is good.

**Comment by AbedElez** [comment]
Please do a factory reset on the phone, and don't install anything else. I am about 99% sure the other apps you have installed are causing this.

**Comment by waterproxy1** [comment]
> Please do a factory reset on the phone, and don't install anything else. I am about 99% sure the other apps you have installed are causing this.

Okay sounds good.
I'll do a factory reset on the phones.
I'll report back after my testing is done!

**Comment by waterproxy1** [comment]
Did a factory reset on a Galaxy S7, still wont connect to my custom server, only connecting to proxidize servers.

**Comment by AbedElez** [comment]
To make sure I understand correctly. You did a factory reset, installed the latest version from the releases with no other apps installed, and the phone still won't work?

I'll be taking a look to find another way to store the information. In the meantime, can you do the same thing on a working phone?

**Comment by waterproxy1** [comment]
> To make sure I understand correctly. You did a factory reset, installed the latest version from the releases with no other apps installed, and the phone still won't work?
> 
> 
> 
> I'll be taking a look to find another way to store the information. In the meantime, can you do the same thing on a working phone?

Yes, that's exactly what I did. 
Factory reset the device. 
Installed latest version of Proxidize.

I will try this on a working device now and let you know the results.

**Comment by AbedElez** [comment]
Got it. Thank you. I will assign an engineer to work on this full-time to get it resolved before the end of next week. Do you have a live chat messaging app you use, such as Skype, Telegram, etc.?

**Comment by waterproxy1** [comment]
> Got it. Thank you. I will assign an engineer to work on this full-time to get it resolved before the end of next week. Do you have a live chat messaging app you use, such as Skype, Telegram, etc.?

You're welcome! Sounds like a plan.
Yes, I use telegram. 
Feel free to message me https://t.me/waterproxy1

**Comment by waterproxy1** [comment]
Quick update!
I did a factory reset on one of the working phones, which is a pixel 3.
I installed the latest a Proxidize android.
Tried connecting to my custom server, and now it's not working. It only connects to the default Proxidize servers.

![image](https://user-images.githubusercontent.com/118281825/212494477-646fa9f9-0ce0-4a46-bd1e-8694480ee90c.jpeg)
![image](https://user-images.githubusercontent.com/118281825/212494482-e7e5668b-3539-4300-83c3-0f71ba8a2672.jpeg)

**Comment by waterproxy1** [comment]
Update!
The Proxidize Engineering Team got into contact with me on Telegram.
I was given a test version of a new Proxidize-Android apk, and everything worked perfectly on all of my devices!
I can confidentially say that when the new version is released, everything will be working flawlessly!
Thank you to the Proxidize Team for allowing me to be apart of fixing this bug, it was a ton of fun experimenting.

**Comment by rocketprogrammer** [comment]
When will this fix be released?

**Comment by waterproxy1** [comment]
> When will this fix be released?

I'd say sometime this week or by next week.
I'm not too sure exactly, since it was an experimental apk. I'm sure it won't take long for the release.

**Comment by AbedElez** [comment]
The update will be shared today or tomorrow. @rocketprogrammer

**Comment by AbedElez** [comment]
Update released. Thanks @waterproxy1 and everyone that helped!

https://github.com/proxidize/proxidize-android/releases/download/v2.1.2/Proxidize.Android.2.1.2.apk
