### ISSUE TITLE
Can't connect to any proxy

### ISSUE THREAD

**Issue by al0nestudio** [proxidize/proxidize-android#34]
Hello, when create a 4g proxy with the app and i try to connect to it i get: "cURL error 7: Failed to connect to 20.21.58.255 port 38323 after 124 ms: Connection refused".
I tired to restart app and data many times but i always get that message.

**Comment by greyxp** [comment]
same

**Comment by evolvepx** [comment]
Same. I've tried on 2 different phones

**Comment by AbedElez** [comment]
You need to deploy your own server. Default servers are at full capacity.

**Comment by hoangthangbk51** [comment]
Hi . I have same problem " Failed to connect to 104.215.113.70 port 43507: Connection refused"
Phone also disconect internet . Can't use teamview to conect .
Im still stuck on that .
Please anyone have any ideal

**Comment by AbedElez** [comment]
It should be good now after the server updates.
