### ISSUE TITLE
Failed to connect to 103.xxxxxxxx port xxxx: Connection refused

### ISSUE THREAD

**Issue by hoangthangbk51** [proxidize/proxidize-android#35]
Dear sir :
Im using custom server but some time it still happen when im press to proxy change link  phone stuck on airplane mode . Can not auto back to connect . 
Do you have any ideal on that . 
This app very nice and help me alot at work . 
thanks you so much.

**Comment by AbedElez** [comment]
What's your phone model and Android/Software versions? I'll send you a temporary solution.

**Comment by hoangthangbk51** [comment]
Thanks for reply . 
My phone is samsung galaxy A20. and Android 11 .
![2](https://user-images.githubusercontent.com/77531950/210098825-5f90a013-1e52-44be-a604-7d60ceb29099.jpg)
![1](https://user-images.githubusercontent.com/77531950/210098816-e9327a0c-27a6-4968-80aa-1bfcdb085725.jpg)

**Comment by AbedElez** [comment]
Make sure the phone is rooted, then use Macrodroid to auto-disable airplane mode if enabled.
