### ISSUE TITLE
Not connected, restart app

### ISSUE THREAD

**Issue by benfrankie** [proxidize/proxidize-android#36]
hi, When I click Connect, it says "Not connected, restart app..." even though the data is working. Any suggestions?

I restarted the app, phone but the issue still persists. 

When I change the server to Europe it says connected but the proxy doesn't work. 

phone: pixel 2

also wondering how I can have the app use data instead of wifi when both wifi and data are activated on the phone?
when Wifi is on, the proxy ip comes from wifi not from data. 

thanks

**Comment by benfrankie** [comment]
Now it says connected but I get proxy error. What's going on?

**Comment by AbedElez** [comment]
Try now and let me know. I've upgraded the default servers
