### ISSUE TITLE
change ip not working

### ISSUE THREAD

**Issue by felipedamacenoteodoro** [proxidize/proxidize-android#39]
Hello note that the ip change is not temporarily because it is going in and out of airplane mode very fast.

Can you increase the activation and deactivation of airplane mode for 5 seconds?

**Comment by AbedElez** [comment]
This has been fixed in the latest version https://github.com/proxidize/proxidize-android/releases/tag/v2.1.1

Please test it and let me know

**Comment by AbedElez** [comment]
Closing this until I hear back from you.
