### ISSUE TITLE
IP Change Link response is 0 and solution for app disconnect from proxy server 

### ISSUE THREAD

**Issue by sergeykomlev** [proxidize/proxidize-android#4]
I tried to change the port by the link and I have the following response:

`Status: 0 (Connection establish problem (read logs))`

Is this pattern correct?

`IP:PORT/change_ip?t=TOKEN`

As I see in proxy server logs connection was established, but the port has not changed by the Proxidize app.

`2022/10/03 22:01:02 [I] [...] [...] [...] get a new work connection: [...]`

**Comment by AbedElez** [comment]
Do you mean change the IP by link?

**Comment by sergeykomlev** [comment]
> Do you mean change the IP by link?

Yes. 

Now I also switched off IP rotation feature. I found that in some reason app is disconnected because of IP rotation freeze. I enabled MacroDroid for IP rotation now.

**Comment by sergeykomlev** [comment]
Yeah, my problem that Proxidize app disconnect from proxy server from time to time.

I created a MacroDroid to open app and push a connect button again. 

It’s will be good to have a custom static login/password for mobile device proxy, because sometimes new login/password generated, maybe because of app crash/close/termination.

**Comment by sergeykomlev** [comment]
My solution for connection break with proxy server based on MacroDroid macros. Hope this will help someone. Auto change of IP should be set to 0. 

My MacroDroid macros template:
[macros.zip](https://github.com/proxidize/proxidize-android/files/9708784/Proxidize_Change_IP_and_cconnect_to_proxy_server_at_disconnect.zip)

![37F09DBA-85F9-41CF-9D04-8CE8964C8EAC](https://user-images.githubusercontent.com/40078038/193870020-58148ff6-d764-4b7d-9c05-1d88b07a7877.jpeg)

**Comment by AbedElez** [comment]
What phone and Android versions are you using? Can you post a screenshot of your software information page on your phone?

**Comment by sergeykomlev** [comment]
> What phone and Android versions are you using? Can you post a screenshot of your software information page on your phone?

Yes, it’s Redmi Note 5 (rooted). I don’t think this will help a lot, because it’s can happen from time to time. Sometimes connection with server can have a freeze. MacroDroid is good solution for that.

But I have another important question. 

When my device offline or have any issue with connection I see that custom proxy server with Proxidize work just as a datacenter proxy server. That’s mean all connections go throw this server, because connection with device is not established.

Is it possible to prevent this behavior and skip outgoing connections via custom proxy server with Proxidize and only allow connection via mobile device? 

Because this issue can cause huge problems in my case.

**Comment by AbedElez** [comment]
I think what's happening here is your phone is closing the app due to battery optimization. Can you check the status on that from your settings?

> Is it possible to prevent this behavior and skip outgoing connections via custom proxy server with Proxidize and only allow connection via mobile device?

In theory, yes. But it depends on your carrier. Read this: https://github.com/proxidize/proxidize-android#using-the-app-without-connecting-to-the-tunneling-server-first

**Comment by sergeykomlev** [comment]
I checked the battery settings. All is fine, optimization options are disabled. I think it's a phone issue.

**Comment by AbedElez** [comment]
Does this happen after a reboot as you've mentioned in the other issue?

**Comment by sergeykomlev** [comment]
> Does this happen after a reboot as you've mentioned in the other issue?

I don’t know, but I think yes.

**Comment by AbedElez** [comment]
I think this is going to be mostly related to the reboot. I'll see what I can do in future updates, but ideally, the phone shouldn't reboot.

**Comment by AbedElez** [comment]
Closing this until I hear back from you @sergeykomlev
