### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by Jerryfr87** [proxidize/proxidize-android#40]
Hi I have tried connecting to my proxy on firefox using foxyproxy add on, but on the browser it keeps saying unable to connect. I have tried other 4g proxies, it works but proxidize app servers does not work. 

It says connected on the app, but cannot connect, browser error “unable to connect”

thanks. 

Phone models:
Samsung z3
Samsung s10+

**Comment by AbedElez** [comment]
Where are you based? Can you paste a screenshot of the output when testing the proxy on Firefox?

**Comment by Jerryfr87** [comment]
![Uploading B337D40F-B9F1-48F7-B171-E63C179ABE6C.jpeg…]()

**Comment by Jerryfr87** [comment]
UK. Try endlessly today still not working. 2 networks have been tried so far EE and Vodafone.

**Comment by Jerryfr87** [comment]
![B3B8519A-508F-4C78-B795-8A2812B7694C](https://user-images.githubusercontent.com/122180925/211222546-083d04a6-8e26-47b4-a902-7dff0c9aa737.jpeg)

**Comment by AbedElez** [comment]
The server could be at full capacity. Try changing the server or deploying your own.

**Comment by AbedElez** [comment]
Marking as closed until I hear back from you.
