### ISSUE TITLE
Getting Connection Error

### ISSUE THREAD

**Issue by abdulraheempk** [proxidize/proxidize-android#41]
Hi I installed your app on 4 Mobile Devices and generated the socks5 and https Mobile proxies. In start it works with my browser but after few hours they stopped working. It shows "Connection Error". Can you please suggest me some solutions to this issue.

**Comment by AbedElez** [comment]
The default servers reach capacity.

Refer to architecture: https://github.com/proxidize/proxidize-android#how-it-works-and-architecture

And deploying your own server: https://github.com/proxidize/proxidize-android#deploying-your-own-server

**Comment by AbedElez** [comment]
Closing this until I hear back from you @abdulraheempk
