### ISSUE TITLE
Connecting to tunneling server within same network

### ISSUE THREAD

**Issue by Sagalicious** [proxidize/proxidize-android#42]
Hi! This is great project and it is in constant use.

Question: If tunneling server is located within the same network as the proxies and the proxy client, is it possible to connect all 3 properly without going to internet and back in for no real use? 

Aim is to mitigate need of having to swapping Wifi constantly and have multiple proxies open at once on same computer and keep higher internet speeds. 

Thank you!

**Comment by AbedElez** [comment]
You would still need to hop to the internet to access the cellular network

**Comment by Sagalicious** [comment]
Hello. Yes phones have internet enabled which are being used for the proxy, but the phones, the server and the client are all located in same room (and access to same LAN) - Wondering if it would be possible to at least connect Client to server through intranet/private IP to speed the connection a little bit.

**Comment by AbedElez** [comment]
What you're describing would be possible once we finish the WIFI backend feature. But it's unclear at the moment when that'll be ready.

Currently, the connection must hop through the web since the carrier network is separate from yours.

**Comment by Sagalicious** [comment]
Alright thank you for clarification. I will look forward to WIFI backend then :)

What about Client <-> Server? Could these be connected through intranet/Private IP to speed it up a little?

**Comment by AbedElez** [comment]
Not without connecting to WIFI which would defeat the purpose of having the phone. I'm closing this for now. Let me know if you need help with anything else.
