### ISSUE TITLE
UDP protocol

### ISSUE THREAD

**Issue by oloho** [proxidize/proxidize-android#45]
Do proxies support UDP/Quic protocol?

**Comment by AbedElez** [comment]
This is a full SOCKS implementation. So you can pass UDP packets freely. SOCKS over UDP support is a matter for your SOCKS client.


I'm leaving this open to hear any feedback from you or other users.

**Comment by oloho** [comment]
Even if the proxy support UDP, Proxifier on win doesn't forward UDP, at this point, what are the win program that support UDP?
Does native proxy win support UDP?

**Comment by AbedElez** [comment]
I can't really think of anything, but it shouldn't be hard to either create a SOCKS wrapper or run a VM that's connected through the proxy.

**Comment by gebran5** [comment]
it is no need to use proxifier in windows , you can setup external adaptor for wifi in your router or in any Linux machine with special iptables rules , for me i use raspberry pi in the home to connect to mobile proxy and then hotspot wifi and make the Windows 11 connect to that wifi and obtain public ip address of the mobile proxy on entire computer .
