### ISSUE TITLE
Auto Change IP API doesn't run

### ISSUE THREAD

**Issue by zaingithub** [proxidize/proxidize-android#46]
Auto Change IP API doesn't run anymore after 30-50x airplane mode.

The response from the API was successful, but on an Android phone, airplane mode has not changed, so the IP address has not changed either.

Where do you think the problem is?

**Comment by AbedElez** [comment]
This is about a tenth of the information I would need to know what's happening.

What's the phone? software version? Android version? has this happened on multiple devices? Was anything changed on the phone? Is the phone rooted? Is the app still the default assistant? Any information you can provide will help me understand what's happening.

**Comment by AbedElez** [comment]
Closing this until I hear back from you.
