### ISSUE TITLE
Custom domain 

### ISSUE THREAD

**Issue by oloho** [proxidize/proxidize-android#48]
Hi

How to have a custom domain instead of proxidize IP server?

how to do this ? how to update the redirection to another port?

subdomain.domain.com:port 1>>>adress:port5

subdomain.domain.com:port 1>>>adress:port9

Also can I know how much data is consumed through the redirection?

**Comment by AbedElez** [comment]
Point an domain A record to the IP of the server. For traffic, a simple google search will show you many options. It should be done on the server.
