### ISSUE TITLE
Prevent proxy credentials change upon restart

### ISSUE THREAD

**Issue by oloho** [proxidize/proxidize-android#49]
Is it possible to not change username/pw/port upon app restart?
also
Sock5 username/pw are not working. You can just use server IP + port then you are connected.

**Comment by AbedElez** [comment]
Which version and phone are you using? This has already been added.

**Comment by oloho** [comment]
I'm trying with th last version.
When I reboot my phone, and on start I reconnect to the proxidize server or my own, the username/pw change, the port is the same though

**Comment by oloho** [comment]
Hi can I have the source code of the APK so I can modify it?

**Comment by jeffgh72** [comment]
Hi, Hope you're well. I'm using the proxy for Instagram automation. So when I put the proxy address in my server the proxy address should not change, Not Ip, port, username, or password. is it possible to fix this issue, please? when we restart the app or doing anything

**Comment by AbedElez** [comment]
Keeping this open until we push the update.

**Comment by AbedElez** [comment]
Fixed with the latest update
