### ISSUE TITLE
App doesn't rotate IP

### ISSUE THREAD

**Issue by bmbra** [proxidize/proxidize-android#50]
Have updated app, and tried on multiple different devices. Set to 2 mins interval, 30 mins. It doesn't auto-change unless I do it manually. And when done manually, it changes the IP user and pass.

Any advice? 

Thanks!

**Comment by oloho** [comment]
I suggest you to use macrodroid to change IP as alternative.

**Comment by AbedElez** [comment]
What is the phone, android version and version of the app you're using?

**Comment by jeffgh72** [comment]
@abedlez, when we set the auto, rotate it doesn't show it saved and when we click on set the auto-rotate it just shows a box to choose the time again and it doesn't show what was your previous set time rotating. Can you confirm this?

**Comment by AbedElez** [comment]
Closing this until someone shares exact model and Android versions they're seeing this with.

**Comment by zenzo22** [comment]
I can confirm that the IP change is **not** working on a Samsung S5 neo, Android 6.0.1. Proxidize (latest version 2.1.4) is set as device assistant app. Using the API or clicking on "change IP" does nothing. 
I have been using the proxidize app on a Galaxy S7 with Android 8.0.0 without any problems for days now. 
Wondering if it is incompatible or something is set wrong on my side as it states that all phones starting Android 6.0* are supported?
