### ISSUE TITLE
Proxifier Socks5 Unsupported Method

### ISSUE THREAD

**Issue by Goelbasi** [proxidize/proxidize-android#52]
When i try to use the Socks5 Method with proxifier it says the error "Proxy Server uses unsupported methods"

**Comment by AbedElez** [comment]
Try testing the SOCKS proxy on FireFox and make sure you're using the correct port.

**Comment by Cowcaz** [comment]
Hi, i have the same issue, cant use my proxy in socks 5, doesnt support methods
