### ISSUE TITLE
Keep proxy parameters the same on device reboot or app full close (termination)

### ISSUE THREAD

**Issue by sergeykomlev** [proxidize/proxidize-android#55]
### About problem
The main issue we have with Proxidize Android app is dynamic proxy credentials changes on device reboot or force app close.

### How to reproduce

1. Open app, click connect, take a credentials screenshot. Reboot phone, open app again and take a credentials screenshot. The proxy credentials (port, username and password) are not the same.

2. Open app, click connect, take a credentials screenshot. Force app stop (not just swipe up close), open app again and take a credentials screenshot. The proxy credentials (port, username and password) are not the same.

But it’s very important to keep credentials the same. 

### How to fix

I think it’s possible to save cridential to local device storage. And even after reboot or force app stop you will be able to use the same credentials. Ideally is to set your own credentials (port, username and password) in app settings like custom server.

**Comment by sergeykomlev** [comment]
Fixed. I created a modified app version with that functionality.

**Comment by alvinlys** [comment]
@sergeykomlev
mind to share your app? tq
