### ISSUE TITLE
Add a proxy control panel

### ISSUE THREAD

**Issue by blackerror1** [proxidize/proxidize-android#56]
my dear
I want to add a proxy control panel that enables me to change the username and password for the proxy, in addition to changing the rotation of the IP change from the panel
In addition to adding a very important feature, which is the whitelist for the IP
I can pay for my own copy
I can pay for my own copy
I can pay for my own copy
can I communicate with you
Thank you

**Comment by AbedElez** [comment]
It's coming soon :)
