### ISSUE TITLE
Unable to connect to 4g android proxy server

### ISSUE THREAD

**Issue by Jirito0** [proxidize/proxidize-android#58]
I’ve set up Proxidize using the latest APK on this GitHub, on a Pixel 3 with 4G service via GoogleFi in the US

The Pixel is able to successfully connect to either the “Auto” server or North America server. But once I enter the Proxy Connection Details into another device (in this instance, the device im trying to connect to the Proxy, is an iPhone 12), I just get the “No Internet Connection” error.

The iPhone is on WiFi, and when entering the Proxy IP address, port, and username/ password (I ensured the username and password were entered correctly several times, and matched the upper/lower case), it just keeps asking me to enter the username and password over and over. 

I’ve tried rotating the Proxy IP address on the Pixel, multiple times, and rebooting multiple times, and changing servers between “Auto” and “North America”

Any other solutions that I can attempt?

**Comment by iamkhalidbashir** [comment]
Yes this happens with custom server too
@abedlez I think it started happening after the feature "Remembering the user name password on app restart"

Because the very  first time (freshly installed app) when the password is generated fresh, we get connected!

After that when we change IP or restart app, the proxy gets disconnected because I think the password changes internally but it shows old password on the dashboard of the app.

**Comment by oloho** [comment]
I was about to update my custom app but I have to wait. Thanks for the feedback

**Comment by iamkhalidbashir** [comment]
When I saw the code of the app I realized its very simple.
So now use "frp" (App on play store) app to run the proxy with my desired config
And us "Rotate Ip proxy server"(App on play store) app to run the change API server

**Comment by AbedElez** [comment]
Fixed with release v2.1.6

**Comment by bannyhm** [comment]
Здравствуйте. К сожалению проблема наблюдается на версии 2.1.6. Подскажите как можно решить эту проблему. 
В скринах видно ошибку https://disk.yandex.ru/d/pvRn0iVOicbf1g

Лог сервера: root@vm583264:~/proxidize-android# 2023/08/02 18:14:16 [I] [service.go:130] frps tcp listen on 0.0.0.0:4000
2023/08/02 18:14:16 [I] [root.go:207] Start frps success
