### ISSUE TITLE
Creating 4G Proxy Fails

### ISSUE THREAD

**Issue by MetaStellar** [proxidize/proxidize-android#59]
When attempting to establish a 4G proxy connection with the Android app, the process consistently fails, despite the app indicating a successful connection. This issue prevents the effective use of 4G proxies, while in contrast, the creation of residential proxies using Wi-Fi proceeds smoothly without any problems. This suggests that the issue lies specifically within the 4G proxy implementation in the app.

When connected to Wi-Fi, the app seamlessly creates residential proxies, with all features and functionalities operating as intended. However, when attempting to establish a 4G proxy by switching to a 4G network and disabling Wi-Fi, the app displays a successful connection, but in reality, the connection cannot be used. I have tried connecting to the 4G proxy through various apps and software, all of which have failed, whereas the residential proxy created via Wi-Fi works perfectly in the same context. This behavior has been consistently observed across multiple attempts, indicating an ongoing issue with the app's 4G proxy implementation.

Edit: In the notifications it shows that I'm connected to the ip:port:null:null instead of ip:port:username:pw
Edit2: With the version before it works well.

**Comment by AbedElez** [comment]
Closing as duplicate for now. We'll be looking into it.
