### ISSUE TITLE
Feature Request: Static values for proxy credentials 

### ISSUE THREAD

**Issue by sergeykomlev** [proxidize/proxidize-android#6]
I found that Proxidize app dynamically generate the login and password for proxy. In my case app sometimes lost connection with proxy server and at reconnect new credentials is generated. I think it’s good to have static values for proxy credentials.

**Comment by AbedElez** [comment]
This is not normal behavior. The app saves the credentials and they should not change even after you restart it.

Which version are you using?

**Comment by sergeykomlev** [comment]
> Which version are you using?

I use v2.1.0; sometimes, in my case, the phone automatically reboots, then I click connect and new credentials are generated.

I think it's good to have the option to set custom credentials for the proxy (user, password, port for HTTP/socks) and save this data in the phone memory. To make this data static.

Are credentials generated on the proxy server level or in the app?

**Comment by AbedElez** [comment]
Why does the phone reboot? Does this only happen after a reboot?

I'll try to replicate this behavior and see what happens.

> Are credentials generated on the proxy server level or in the app?

Anything credentials or authentication related is done in the app itself.

**Comment by sergeykomlev** [comment]
> Anything credentials or authentication related is done in the app itself.

I will wait for the app code, because I think I will be able to push improvements here.

In my case custom server settings are saved and even after reboot not changed, I have only one problem with credentials, which are regenerated sometimes.

**Comment by AbedElez** [comment]
I'm working on the next update so I'll be adding that.

Do the credentials change for you if you exit and restart the app? Specifically when using the exit button?

**Comment by sergeykomlev** [comment]
> Do the credentials change for you if you exit and restart the app? Specifically when using the exit button?

- when I his the Exit button (this happened not always)
- when I have device reboot
- when my phone terminate app in backgroud

I was able to fix disconnect using MacroDroid, simply hitting Connect button. But my main problem is new user/pass/port cridentials for proxies. They are changing somehow and this breaks my connection with proxy server.

Anyway thanks for your replies. I will wait for new updates.

**Comment by AbedElez** [comment]
Try the latest version and let me know. The credentials should only change if you delete the app.

**Comment by AbedElez** [comment]
Closing this until I hear back from you @sergeykomlev
