### ISSUE TITLE
API Link is broken.

### ISSUE THREAD

**Issue by waterproxy1** [proxidize/proxidize-android#61]
Testing on a T-Mobile Revvlry Android phone, using the latest proxidize android version.
This is the error message I get when trying to use the API Link. 
I tried copying it from the phone and using it that way, same result.
What is the issue here? 
![image](https://user-images.githubusercontent.com/118281825/236554228-465d3f9a-86aa-484c-ba56-ef4ae1f3dc99.png)

**Comment by AbedElez** [comment]
Is this happening to a single phone/model or all? Did it work before the last update?

**Comment by waterproxy1** [comment]
Happening with multiple phones.
Some phones get lucky and work with api link while some do not.
I will test on a few more devices to see.

**Comment by AbedElez** [comment]
Please test v2.1.6 to see if the issue persists

**Comment by AbedElez** [comment]
Please test v2.1.6 to see if the issue persists

**Comment by waterproxy1** [comment]
Okay, I will test and let you know, thank you brother

**Comment by Afuhuu** [comment]
> Please test v2.1.6 to see if the issue persists

It's happening for me too

**Comment by waterproxy1** [comment]
Tested v2.1.6 with a Pixel 4a 5G and same issue has happened. 
I rebooted the device and then it worked for sometime, but then soon after the API link started displaying the same message.

**Comment by AbedElez** [comment]
@waterproxy1 did you allow the app to ignore battery optimization? It sounds like the process is getting killed by the phone after a while.
