### ISSUE TITLE
 Syntax error: end of file unexpected (expecting ")")

### ISSUE THREAD

**Issue by radwanho** [proxidize/proxidize-android#62]
i get this error when i try to run the server
./server/server: 1: Syntax error: end of file unexpected (expecting ")")

Operating System: Ubuntu 22.04.2 LTS
Architecture: arm64

how can i solve this problem and thank you

**Comment by AbedElez** [comment]
You're using an ARM CPU server. You need an x86-64/amd64 sever

**Comment by radwanho** [comment]
thank you for your response
