### ISSUE TITLE
Latest code is not pushed in this repo

### ISSUE THREAD

**Issue by iamkhalidbashir** [proxidize/proxidize-android#63]
I have noticed that this repo is not updated.
I have old code that was initially commented on a year ago which is very outdated.
The author of this repo seems to just change the URL of the download link in the Readme file without updating the code which seems a little suspicious to use the download link (especially as a proxy).

Could the latest code be pushed in this repo?

**Comment by iamkhalidbashir** [comment]
May be @abedlez @YamenAlazzam1 can chime in.

**Comment by AbedElez** [comment]
Feel free to use the original version until we release the rest of the code later on. There's a licensing issue we need to deal with internally.

**Comment by iamkhalidbashir** [comment]
hmmm
