### ISSUE TITLE
can 5G CGNAT be used proxy

### ISSUE THREAD

**Issue by desis123** [proxidize/proxidize-android#64]
My question is can 5G CGNAT home internet be used as proxy, can I change the ip address of 5G CGNAT home internet? because as far I know CGNAT does not provide any pubic ip address, so how I can change the ip address of those type of network ? I am not clear about the whole concept how it works, can anyone please make it clear

**Comment by AbedElez** [comment]
This app bypasses CGNAT via reverse tunneling. Please refer to the diagram in the Readme file
