### ISSUE TITLE
Issue while using the proxy

### ISSUE THREAD

**Issue by SurajBhari** [proxidize/proxidize-android#68]
I was making [a wrapper](https://github.com/AG4lyf/proxidize_wrapper) for this. but when i do use it. it works with CLI curl. but when used with requests.get. it just gets me ip of the machine instead of getting me ip of proxy. 
I need to use request.get to utilize it. 

is there something am missing ? or misunderstood ?

**Comment by SurajBhari** [comment]
it works fine while using a firefox session with proxy setup
but what is the point if i can't make GET request.

you can see code [here](https://github.com/AG4lyf/proxidize_wrapper/blob/5c2c42b8d85b3f9309d2593d2d3a7c0a8bc7cbd0/proxidize_wrapper/proxidize_wrapper.py)

although if i use urllib instead of requests. it works. is there anything am missing ?

**Comment by AbedElez** [comment]
It sounds like you're not connecting through the proxy. I'll try to take a look once I have a minute.

**Comment by SurajBhari** [comment]
No updates ? @AbedElezz fixed ?
