### ISSUE TITLE
Day 4 of requesting to fix api error 

### ISSUE THREAD

**Issue by Afuhuu** [proxidize/proxidize-android#70]
Please fix api error 
{"response":"invalid password"}
Edit
Re-started app and it says successful
But still not changing ip or toggling airplane mode

**Comment by richdevid** [comment]
What I know is that you need to reselect Google as your voice assistant, then select Proxidize again as your voice assistant. It should work.

**Comment by AbedElez** [comment]
What's the Android version and phone model? Are you connected to wifi or data? And are you sure you're copying the link exactly as is? Did you follow all the instructions for giving the app the requested permissions?

I'm not able to replicate this with the latest version.

**Comment by Afuhuu** [comment]
> What's the Android version and phone model? Are you connected to wifi or data? And are you sure you're copying the link exactly as is? Did you follow all the instructions for giving the app the requested permissions?
> 
> I'm not able to replicate this with the latest version.

Android 11 poco m2 pro
Connected to data
And I'm pretty sure I've gave all permission cause it's toggling airplane mode when I click "change ip"
And also reselected proxidize as assistant still not working
I can provide you more information if i can contact you personally

**Comment by Afuhuu** [comment]
And also proxy doesn't seem working, i tested it on hide.me proxy checker

**Comment by AbedElez** [comment]
Tested working on 60+ models. I'll test your model once I have the time.
