### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by drtiwarir** [proxidize/proxidize-android#72]
Thanks, great work.
I am thinking to deploy my own server (DigitalOcean), but have 1 question. In the app settings we have option of username  & password, when I deploy my server I can use Token to authenticate.
I use Macbook to connect to proxy, there is no option to use Token, it needs username and password, so how can I connect ?
Please advise.

**Comment by ssthormess** [comment]
You are confused. The token is used to authenticate connections from Android app to your server.
You will get username and password to enter in your Macbook settings once you connect in the phone screen. This isn't an issue.

**Comment by drtiwarir** [comment]
Thanks

**Comment by AbedElez** [comment]
Feel free to reopen if you need any help!
