### ISSUE TITLE
Issues on redmi devices

### ISSUE THREAD

**Issue by SaifHash** [proxidize/proxidize-android#74]
Proxidize app doesn't work on redmi devices properly please fix it I have tried it on several redmi devices all having same problem
The problem is it doesn't change IP address on redmi devices it doesn't turn on/off aeroplane mode with link or with clicking change IP address manually on app the aeroplane mode won't turn on/off. once you install proxidize app & give all the permission it will work properly for 1-2 time but after that it will stop working & wont turn on off aeroplane mode

**Comment by oloho** [comment]
Use Samsungs only. Others brands have too much restrictions

**Comment by AbedElez** [comment]
We'll be getting to Redmi devices in a few months. It's not a priority at the moment.
