### ISSUE TITLE
DNS proxy

### ISSUE THREAD

**Issue by drtiwarir** [proxidize/proxidize-android#75]
It's a question, not a issue.
I am from regional place in India, I do travel overseas a lot, was thinking to use proxidize as a smart DNS proxy.
My plan is to install Dnsmasq on a digitalocean droplet and filter few domains to go through proxidize.
Will it work ?
Can I disable user and password in the proxidize app ? Because Dnsmasq does not support it.
Your help is appreciated.
Thanks

**Comment by AbedElez** [comment]
Technically, you can. But it would be a massive security issue. We'd be unlikely to add this.

Please feel free to make any other suggestions or recommendations.
