### ISSUE TITLE
Issue with using proxy

### ISSUE THREAD

**Issue by robertskieren6** [proxidize/proxidize-android#76]
Hi, all,

First-time user, 

Downloaded the app and am getting this error every time i press connect.

"Not Connected, Restart app and connect again"

Tried changing the server & fingerprint. 

Any ideas on how to fix it?

**Comment by robertskieren6** [comment]
Phone is : Samsung Galaxy S10e

Android Version : 12

Location : United Kingdom

**Comment by Protey** [comment]
I confirm, it is impossible to connect, it constantly displays a message "Not Connected, Restart app and connect again"!
Phone is : Tecno SPARK 8C
Android Version : 11
Version app - Proxidize Android Legacy v2.1.6
Used different servers - US West, EU East, EU West and Auto
When changed, as expected, restarted the application

![proxidize](https://github.com/proxidize/proxidize-android/assets/6497045/474d5cac-d583-4391-bf3f-768e187c9d2b)

**Comment by VVVAAAVVV** [comment]
"Not Connected, Restart app and connect again" I have the same problem

**Comment by nevstas** [comment]
I have the same problem.

Proxidize Android Legacy v 2.1.6
Android v 13

Clear cache helped me. But I have to do it constantly

**Comment by robertskieren6** [comment]
Any fix? been 2 weeks Has project been abandoned?

**Comment by ssthormess** [comment]
Project works fine. Check your logs.

**Comment by AbedElez** [comment]
We ran a server update a while back. Always try to deploy your own servers when possible, as default servers are near capacity.

Please reply here if you're still having the issue.

**Comment by nevstas** [comment]
I have the issue.

- I have cleared cache.
- I have run the app and tried to connect - connection sucess.
- I have closed app
- I have run the app again and tried to connect - Not Connected, Restart app and connect again

Proxidize Android Legacy v 2.1.6
Android v 13

**Comment by iisbetoq** [comment]
> We ran a server update a while back. Always try to deploy your own servers when possible, as default servers are near capacity.
> 
> Please reply here if you're still having the issue.

IMO, the problem is with several cellular operators, my case is in Indonesia with XL Axiata, what I have done:

- mutually changing the APN is still the same
- mutually replace OS A10, A11, A12 still the same
- mutually changing application versions, 2.16, 2.15 are still the same
- use shared server or own server are still the same

but if you use a similar application with the XL Axiata carrier there is no problem

for other cellular operators such as IM3/3, Telkomsel there is no problem with Proxidize Android Legacy

**Comment by trebor678** [comment]
> I have the issue.
> 
> * I have cleared cache.
> * I have run the app and tried to connect - connection sucess.
> * I have closed app
> * I have run the app again and tried to connect - Not Connected, Restart app and connect again
> 
> Proxidize Android Legacy v 2.1.6 Android v 13

I have the same issue. Have to keep clearing the app data if I kill the app. If you click on 'Exit' within the app them it's fine. Definitely a bug

**Comment by ssthormess** [comment]
This happened to me in the very rare case when there is a previous session that wasn't closed using the button (crash, reboot, update, no battery, etc.) in the app so when the Android client tries to connect again the server logs that the port is already in use. However if you click the exit button it will close the session and when you open the app again anytime it will connect and resume working properly.
