### ISSUE TITLE
How to raise your own server to use the Proxidize application?

### ISSUE THREAD

**Issue by Protey** [proxidize/proxidize-android#77]
I ask you to write a step-by-step instruction so that it is inside and out how to raise your own server to use the Proxidize application.
The [instruction](https://github.com/proxidize/proxidize-android#deploying-your-own-server) that is, in the form of an example, it is not clear, a more understandable instruction is needed!

**Comment by SaifHash** [comment]
True there should be more guide about servers

**Comment by ptraced** [comment]
its so simple read those it takes 5 mins bro.

**Comment by Protey** [comment]
> its so simple read those it takes 5 mins bro.

If it was so easy for me, I wouldn't post here!
Can you make a video instruction?

**Comment by Hostrdp** [comment]
The steps are clear as day.
Which steps that you're not understand?
