### ISSUE TITLE
[Question] Create bulk proxies?

### ISSUE THREAD

**Issue by Hostrdp** [proxidize/proxidize-android#79]
Hello Team,

Thank you for your awesome projects!
Anyway this is only create 1 Mobile Proxy at a time, per phone right?
is it possible to create bulk proxies per phone at a time?

**Comment by SaifHash** [comment]
Not possible bro you need to buy proxidize proxy kit for creating bulk proxies

**Comment by oloho** [comment]
thre another solution is to create backconnect proxies

**Comment by AbedElez** [comment]
The limitation is the unique egress IPs. In theory, you create an unlimited number of proxies on the phone itself, but they would all share the same public IP address.
