### ISSUE TITLE
Proxidize Android Legacy V2+ Source Code

### ISSUE THREAD

**Issue by AbedElez** [proxidize/proxidize-android#8]
This is will be an open issue to maintain updates about fully publishing the source code of PAL V2, which I plan to finish soon. Just need to finish the updated license. I'll be sharing any updates or changes here.

From a licensing perspective, we might need to publish the code without access to any of the Proxidize servers, which in turn, might have us remove the default servers from any future release, which will be counter-productive for non-technical users. So one thing I'm considering is publishing the new components in a separate repo with instructions for compiling everything together.

**Comment by snorlax1998** [comment]
Hello. I have deployed my own server, but the program gives random ports and data, can I somehow choose the port and data myself? It is not convenient to open many ports at once.

**Comment by ninotker** [comment]
when will you 
release source code of v2 ?

**Comment by oloho** [comment]
Hi

Can you release the code source of the APK? I really need this

**Comment by AbedElez** [comment]
@oloho It's released under the dev branch. Will merge in a few weeks once I fix the outstanding bugs.

**Comment by oloho** [comment]
it's not the same as the 

https://github.com/proxidize/proxidize-android/releases/download/v2.1.4/Proxidize.Android.Legacy.v2.1.4.apk

**Comment by AbedElez** [comment]
Please explain how you think it's not the same as the latest release.

**Comment by oloho** [comment]
I got this 
![image](https://user-images.githubusercontent.com/119107632/222779488-6a3e12a1-0150-4dc8-b071-18bcf2aea52e.png)

**Comment by AbedElez** [comment]
You need to use the _**dev**_ branch.

**Comment by oloho** [comment]
ok thanks I use th branch dev but I cannot use the porxies generated, proxies are denied

![image](https://user-images.githubusercontent.com/119107632/222893485-4ccb8378-8ebc-4822-bb97-40e11fa5c8ac.png)
![image](https://user-images.githubusercontent.com/119107632/222893511-0b6a0494-c762-43cc-997f-0b4bb26e578a.png)

**Comment by oloho** [comment]
I use this modified apk
https://drive.google.com/file/d/1yfWfxuWV9sJa2pHD9AvFcxK1kkiYtW6F/view?usp=sharing

Can you tell me where I do wrong?

**Comment by oloho** [comment]
It's all good I got the right sompiled APK

May I ask what is "Wifi Backend"  and are you working on the "Fingerprint"? what do you need to somplete this feature? I can have some help.

**Comment by AbedElez** [comment]
Closing as complete.
