### ISSUE TITLE
After refreshing IP address via URL the server refuses to connect unless restarted

### ISSUE THREAD

**Issue by ssthormess** [proxidize/proxidize-android#80]
Hi,

I am running several clients using the server without issue. 

However after a client IP address gets refreshed via the URL provided further Refresh IP requests won't be able to connect and will end up timing out. 

For now, I am restarting the whole server process when this happening but I would like to ask if anyone knows more about this or is facing this issue.

**Comment by SaifHash** [comment]
Were you able to solve this problem? I am having same issue

**Comment by SaifHash** [comment]
Earlier it was working fine

**Comment by AbedElez** [comment]
> For now, I am restarting the whole server process when this happening but I would like to ask if anyone knows more about this or is facing this issue.

We'll be taking a look shortly. Can you please clarify this?

**Comment by ssthormess** [comment]
Hi,

For now I have a script checking the server logs every minute and restarting the "server" process if there are no changes/server is stuck.
