### ISSUE TITLE
spikes of CPU and RAM usage

### ISSUE THREAD

**Issue by oloho** [proxidize/proxidize-android#83]
Hi

I host a mobile proxy server for months and monthsit's going well and then suddenly my server record a spike ot CPU, I have nothing change for months.
I sell my proxies, and my clients are the same for a couple months.
Suddendly; yesterday, my vps got  spikes of CPU usage and of course the proxy server is down every time.

Where this is coming from?

One of my client can send a lot requests/threads and my server can't handdle it?
someone is attacking my server or?
I don't know what going on, and how to find the cause.

**Comment by apradipta10** [comment]
same as me, up. hope for the answer

**Comment by ssthormess** [comment]
same up

**Comment by AbedElez** [comment]
There can be dozens of things that can cause this. From a client using a lot of traffic to a misconfiguration in the server's firewall, leaving you vulnerable to attacks.

Check the traffic to confirm it's normal, and make sure you have up-to-date firewall rules.

**Comment by ssthormess** [comment]
For me I just switched to another provider and it worked so it was a hardware issue.
