### ISSUE TITLE
Proxidize does't show up on Default digital assistant app

### ISSUE THREAD

**Issue by alexguemezx** [proxidize/proxidize-android#84]
Hi guys.

I bought a Hisense U30 (Android Version 11), I know is a cheap phone but I'm trying to buy several phones and see how they work.

When I open Proxidize it ask me to set Default Assistant.
I click on "SET". Then I click "Default digital assistant app" and Proxidize is not there.

Image: https://ibb.co/L8F0vrf

I have been able to setting up on an Samsung phone but not on this one.

Is there a way to add Proxidize if is not on the list?

If I try to connect I get "Not connected, Restart app and connect again".

**Comment by richdevid** [comment]
Yes, I don't think it supports Android Go yet. I have a cheap Android device that uses Android Go as well, and Proxidize is not listed in the digital assistant app. So, I use ADB to change the IP.
