### ISSUE TITLE
Setsid Permission Error On AWS Lightsail 

### ISSUE THREAD

**Issue by charmingdream** [proxidize/proxidize-android#87]
Hello

I tried deploying the script to my own server, using AWS lightsail aand got stuck at this command:
setsid ./server/server -c ./server/server.ini &
It throws permission denied error, have tried using sudo and same error.
root@localhost:~/proxidize-android# setsid: failed to execute ./server/server: Permission denied

**Comment by iisbetoq** [comment]
chmod +x ./server/server

> Hello
> 
> I tried deploying the script to my own server, using AWS lightsail aand got stuck at this command: setsid ./server/server -c ./server/server.ini & It throws permission denied error, have tried using sudo and same error. root@localhost:~/proxidize-android# setsid: failed to execute ./server/server: Permission denied

chmod +x ./server/server

**Comment by charmingdream** [comment]
Thanks so much, worked.
