### ISSUE TITLE
Hosted proxy wont works

### ISSUE THREAD

**Issue by PetraChristalbert** [proxidize/proxidize-android#88]
I created my own proxy with ubuntu, i open the port 51523, ACCEPT at all sudo iptables -S, the proxy details showed, and then time to use the proxy.
![image](https://github.com/proxidize/proxidize-android/assets/151901650/5326c5be-6538-47d2-b577-a50961a27347)

but the proxy didnt work at all... I am really confused, tried everything for 2 days... Hopefully there is something i need to fix...
![image](https://github.com/proxidize/proxidize-android/assets/151901650/54b5cfd2-a92a-4cda-b60c-2307c619d1d2)

Just for information, i am using Ubuntu VM from VULTR. I tried to use the default proxy from Proxidize and it totally works. but the proxies i made by deploying own server is just doesnt works at all...

_Originally posted by @PetraChristalbert in https://github.com/proxidize/proxidize-android/issues/66#issuecomment-1825192011_

**Comment by PetraChristalbert** [comment]
Okhay i figure it out what really happen and the solution for whoever experinced this that u create the server, host the proxy and got the credential (IP:port:user:pass) but got no internet when connect to the created proxies...

The solution of that problem is "OPEN PORT". Simply just enable incoming port 1 to 65534.

Why? Well, do you remember that when u connect Proxidize to generate proxies, the created proxies crediential showed random 5 digit port on it. So when u connect to that proxies with the random 5 digit port to the server, the server will refuse to let u in because that port isnt public (opened) yet to be access by other device. So u need to open every possible port (1 to 65534) to make sure whatever incoming request, your server will allow it!

I am not the first one who find out about this, i just searched on every issue and accidentally find a guy that say something similar but the way he said is too simple and questionable (less information) as "open range of port" and here I am thinking about it and finally figure it out that what he mean is the solution of similar problem...

**Comment by AbedElez** [comment]
Make sure to take all the necessary security precautions before opening all the ports as that can be risky. Especially system-reserved ports 1-1024.

**Comment by Cowcaz** [comment]
> Okhay, je comprends ce qui se passe réellement et la solution pour celui qui a vécu cela: créez le serveur, hébergez le proxy et obtenez les informations d'identification (IP: port: utilisateur: pass), mais n'obtenez pas d'Internet lorsque vous vous connectez aux proxys créés.
> 
> La solution à ce problème est "OPEN PORT". Activez simplement le port entrant 1 à 65534.
> 
> Pourquoi? Eh bien, vous souvenez-vous que lorsque vous connectez Proxidize pour générer des proxys, les informations d'identification du proxy créées affichaient un port aléatoire à 5 chiffres. Ainsi, lorsque vous vous connectez à ce proxy avec le port aléatoire à 5 chiffres du serveur, le serveur refusera de vous laisser entrer car ce port n'est pas public (ouvert) et n'est pas encore accessible par un autre appareil. Vous devez donc ouvrir tous les ports possibles (1 à 65534) pour vous assurer que quelle que soit la demande entrante, votre serveur l'autorisera !
> 
> Je ne suis pas le premier à découvrir cela, j'ai juste cherché sur chaque problème et j'ai accidentellement trouvé un gars qui dit quelque chose de similaire mais la façon dont il l'a dit est trop simple et discutable (moins d'informations) en tant que "gamme de port ouverte" et ici J'y réfléchis et je comprends enfin que ce qu'il veut dire est la solution d'un problème similaire...

Hi guys, my proxies are ok in https but not in socks5, can u explain me how can i do ? 

thanks
