### ISSUE TITLE
IP Change link and button not working 

### ISSUE THREAD

**Issue by eugunior** [proxidize/proxidize-android#89]
IP address changes only if I turn ON/OFF airplane mode by myself

**Comment by eugunior** [comment]
The best part is that the response is {'response': 'success'}. But IP is not changing

**Comment by iisbetoq** [comment]
is **Digital assistant app** have change default to **Proxidize Android Legacy** ?

**Comment by monkey-friend** [comment]
@AbedElezz @YamenAlazzam1  hey FYI, I'm getting this issue to. I narrowed it down to only happening when I close the proxidize app and then restart it or reconnect. Then I cant change IP anymore.

However, I noticed that it works again I when change the default assistant app to some other app, and then grant proxidize the default assistant app again. Then I can successfully change the IP properly. 

^ This behaviour has been confirmed on:
- Samsung galaxy S6, running android 7
- Techno POVA running android 12

Hope that helps with debugging. If you dont have time, I'd love to help out if you had any hunches you can share too. 

BTW, thanks for an awesome repo! 💪
