### ISSUE TITLE
can't start server

### ISSUE THREAD

**Issue by sdproweb** [proxidize/proxidize-android#9]
hello, can't star server with commande line "setsid ./server -c ./server.ini &"
error showing "setsid: failed to execute ./server: No such file or directory"

any suggetion please? thansk for help

**Comment by ginopalazzo** [comment]
You need to be inside the server directory of proxydize

**Comment by AbedElez** [comment]
There's an error in the docs I need to fix. You need to `cd ./server` then run the command.

**Comment by sdproweb** [comment]
so fast support
ok let me check ;)))

**Comment by sdproweb** [comment]
ITS WORKING!!!!!!!
you just a genius bro!! god bless you

**Comment by AbedElez** [comment]
Reopening this so I don't forget about it.

**Comment by sdproweb** [comment]
👍👍

**Comment by WesleyMarinho** [comment]
Here still no success in generating a connection using my server... How can I fix this please
?

**Comment by AbedElez** [comment]
Closing this as duplicate.
