### ISSUE TITLE
Issus about proxy server 

### ISSUE THREAD

**Issue by manwong0621** [proxidize/proxidize-android#94]
I followed your instruction and run 
the screen shows:
[service.go:130] frps tcp listen on 0.0.0.0:2000
[1] [root.go:207] Start frps success

but 0.0.0.0 is not true , how to connect server real IP?
any way can tackle this problem? Do you have a detailed instruction manual?
Thank you

**Comment by iisbetoq** [comment]
change custom server on your android app, default is (this if you not changed server.ini)
host : your server IP
bind : 2000
token : 12345678

**Comment by matheusbranhan** [comment]
> change custom server on your android app, default is (this if you not changed server.ini)
> host : your server IP
> bind : 2000
> token : 12345678

How to get this token?

**Comment by AbedElez** [comment]
Read this @matheusbranhan https://github.com/proxidize/proxidize-android?tab=readme-ov-file#deploying-your-own-server
