### ISSUE TITLE
not wIt doesn't work without wifi.

### ISSUE THREAD

**Issue by serhat961** [proxidize/proxidize-android#95]
It connects to the proxy only when the Wi-Fi is open. However, even when connected in this way, when I check the IP, it shows the IP of the connected Wi-Fi. It doesn't work with proxies when not on Wi-Fi.

**Comment by JohnnyOmm** [comment]
Im getting same issue. and im testing the proxy for first time and doesnt work says no internet even though it connected on the app successfully
