### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by matheusbranhan** [proxidize/proxidize-android#96]
How make one custom server?

**Comment by AbedElez** [comment]
Read this https://github.com/proxidize/proxidize-android?tab=readme-ov-file#deploying-your-own-server

**Comment by matheusbranhan** [comment]
> Read this https://github.com/proxidize/proxidize-android?tab=readme-ov-file#deploying-your-own-server

Sorry, I couldn't identify how to create a custom server, I saw how to create a proxy server, but not a custom server to use with my proxy.

**Comment by matheusbranhan** [comment]
> Read this https://github.com/proxidize/proxidize-android?tab=readme-ov-file#deploying-your-own-server

Sorry, I couldn't identify how to create a custom server, I saw how to create a proxy server, but not a custom server to use with my proxy.

**Comment by JohnnyOmm** [comment]
> > Read this https://github.com/proxidize/proxidize-android?tab=readme-ov-file#deploying-your-own-server
> 
> Sorry, I couldn't identify how to create a custom server, I saw how to create a proxy server, but not a custom server to use with my proxy.

google ubuntu server install minimized
