### ISSUE TITLE
Absence of Change IP Feature in Source Code v2.1.6

### ISSUE THREAD

**Issue by pulichers** [proxidize/proxidize-android#99]
I am reaching out to address a discrepancy I have noticed between two versions of the Proxidize Android application, specifically version 2.1.6.

Upon downloading and examining the pre-built APK available at app-release APK link, I observed that it includes the following features: CONNECT, CHANGE IP, and AUTO CHANGE IP buttons.

However, when I build the application from the source code provided at source code ZIP link, the resulting APK shows a different set of features: CONNECT, COPY PROXY TO CLIPBOARD, and CUSTOM SERVER buttons.

For consistency and to meet the needs of our workflow, could you please integrate the AUTO CHANGE IP feature into the APK built from the v2.1.6 ZIP source as well?

**Comment by ssthormess** [comment]
Hello. Did you find a way to toggle airplane mode on/off? This version does not show a reset port, nor change or auto change buttons.

**Comment by ThibautChaz** [comment]
Indeed, on the latest version of the releases, the proxy seems to be working. I'm using it, but still, it doesn't change my IP address.
